### ISSUE TITLE
slush-angular with SlushJS 1.0.1 doesn't work on Yosemite 10.10.1

### ISSUE THREAD

**Issue by solidevolution** [slushjs/slush#25]
[slush] Using slushfile /usr/local/lib/node_modules/slush-angular/slushfile.js
[17:01:15] Starting 'angular:default'...
[?] What do you want to name your AngularJS app? test
[?] What CSS preprocessor do you want to use? LESS
[?] Do you want to use CoffeeScript in your app? No
[?] Do you want to include a Todo List example in your app? No

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: undefined is not a function
    at Transform._transform (/usr/local/lib/node_modules/slush-angular/node_modules/gulp-template/index.js:19:31)
    at Transform._read (/usr/local/lib/node_modules/slush-angular/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/usr/local/lib/node_modules/slush-angular/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/slush-angular/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/slush-angular/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/usr/local/lib/node_modules/slush-angular/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_writ⏎

**Comment by joakimbeng** [comment]
Still having a problem with this? If so this should be posted in the slush-angular repo.
